<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-10T20:31:32 IST" name="Suite" finished-at="2024-07-10T20:32:02 IST" duration-ms="30499">
    <groups>
      <group name="ErrorValidation">
        <method signature="errorValidation.errorValid()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" name="errorValid" class="practiceProject.frameworkDesign.errorValidation"/>
        <method signature="errorValidation.producValid()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" name="producValid" class="practiceProject.frameworkDesign.errorValidation"/>
      </group> <!-- ErrorValidation -->
    </groups>
    <test started-at="2024-07-10T20:31:32 IST" name="StandAloneTest" finished-at="2024-07-10T20:31:32 IST" duration-ms="8">
    </test> <!-- StandAloneTest -->
    <test started-at="2024-07-10T20:31:32 IST" name="Error Validation" finished-at="2024-07-10T20:32:02 IST" duration-ms="30499">
      <class name="practiceProject.frameworkDesign.errorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:31:32 IST" name="launchApplication" finished-at="2024-07-10T20:31:34 IST" duration-ms="2847" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorValid()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:31:34 IST" name="errorValid" finished-at="2024-07-10T20:31:35 IST" duration-ms="906" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Incorrect email password.> but was:<Incorrect email or password.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Incorrect email password.> but was:<Incorrect email or password.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at practiceProject.frameworkDesign.errorValidation.errorValid(errorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValid -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:31:35 IST" name="teardown" finished-at="2024-07-10T20:31:36 IST" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:31:36 IST" name="launchApplication" finished-at="2024-07-10T20:31:38 IST" duration-ms="2810" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="producValid()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:31:38 IST" name="producValid" finished-at="2024-07-10T20:32:02 IST" duration-ms="23531" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at practiceProject.frameworkDesign.errorValidation.producValid(errorValidation.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- producValid -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:practiceProject.frameworkDesign.errorValidation@5e82df6a]" started-at="2024-07-10T20:32:02 IST" name="teardown" finished-at="2024-07-10T20:32:02 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- practiceProject.frameworkDesign.errorValidation -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
